In [2]:
import numpy as np
a=np.array([6,7,9,10])
b=np.array([5,6,8,11])
x=np.where(a>=b)
x


(array([0, 1, 2]),)

In [ ]:
a

array([1, 2, 3, 4])

In [ ]:
b

array([5, 6, 8, 9])

In [ ]:
print(x)

(array([], dtype=int64),)


In [9]:
v=np.array([1,5,6,5,7,2,4,3,5])
y=np.where((v%2)==0,0,v)
y

array([1, 5, 0, 5, 7, 0, 0, 3, 5])

In [56]:
a=np.array([1,2,3,4,5,6,7])
b=[1,2,3,4,5,6,6]
c=a[b]
c

array([2, 3, 4, 5, 6, 7, 7])

In [24]:
import math
def isprime(n):
  if n<=1:
    return 0
  if n==2:
    return 1
  if n%2==0 and n>2:
    return 0
  div=int(math.sqrt(n))
  for i in range(3,div+1,2):
    if n%i==0:
      return 0
  return 1

a=np.array([2,5,6,7,8,9,1,4,11,13])
b=[]
for ele in a:
  if isprime(ele)==1:
    b.append(ele)
print(b)
    
  

[2, 5, 7, 11, 13]


In [57]:
a=np.array([2,5,6,7,4,5])
a.reshape(2,-1)

array([[2, 5, 6],
       [7, 4, 5]])

In [43]:
barray=np.array([0,1,1,0,1,0,1,0,0])
barray=map(lambda x:True if x==1 else False,barray) 
print(*barray)

False True True False True False True False False


In [71]:
a1=[]
for i in range(10):
  a1.append(int(input()))
a1=np.array(a1)
a11=a1[0:2]
a12=a1[2:4]
a13=a1[4:]
print("main array",a1)
print("array 1",a11)
print("array 2",a12)
print("array 3",a13)

1
6
9
14
32
74
98
20
5
10
main array [ 1  6  9 14 32 74 98 20  5 10]
array 1 [1 6]
array 2 [ 9 14]
array 3 [32 74 98 20  5 10]


In [77]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [78]:
import pandas as pd
path="/content/drive/MyDrive/Salary_Data.csv"
df=pd.read_csv(path)  

In [79]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   YearsExperience  30 non-null     float64
 1   Salary           30 non-null     float64
dtypes: float64(2)
memory usage: 608.0 bytes
None


In [80]:
print(df.head(5))

   YearsExperience   Salary
0              1.1  39343.0
1              1.3  46205.0
2              1.5  37731.0
3              2.0  43525.0
4              2.2  39891.0


In [81]:
print(df.describe())

       YearsExperience         Salary
count        30.000000      30.000000
mean          5.313333   76003.000000
std           2.837888   27414.429785
min           1.100000   37731.000000
25%           3.200000   56720.750000
50%           4.700000   65237.000000
75%           7.700000  100544.750000
max          10.500000  122391.000000


In [83]:
print(df.sample(n=5))

    YearsExperience    Salary
7               3.2   54445.0
26              9.5  116969.0
8               3.2   64445.0
28             10.3  122391.0
29             10.5  121872.0
